# Generated by Django 3.1.3 on 2020-11-14 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='option1_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='survey',
            name='option2_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='survey',
            name='option3_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='survey',
            name='option4_count',
            field=models.IntegerField(default=0),
        ),
    ]
