# Generated by Django 3.1.3 on 2020-11-14 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20201114_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='option1_count',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='survey',
            name='option2_count',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='survey',
            name='option3_count',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='survey',
            name='option4_count',
            field=models.IntegerField(),
        ),
    ]
