# Generated by Django 3.0.5 on 2020-11-03 08:53

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('middlename', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('date_of_birth', models.DateField()),
                ('twitter_handle', models.CharField(max_length=20)),
                ('fb_handle', models.CharField(max_length=20)),
                ('insta_handle', models.CharField(max_length=20)),
                ('telephone', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('address1', models.TextField()),
                ('address2', models.TextField()),
                ('city', models.TextField()),
                ('state', models.TextField()),
                ('profile_pic', models.ImageField(upload_to='')),
                ('about', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'profiles',
            },
        ),
    ]
