# Generated by Django 3.0.5 on 2020-11-03 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20201103_0201'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='zipcode',
            field=models.IntegerField(blank=True, max_length=5, null=True),
        ),
    ]
